[AnalogBinds]
; for wooting - axis = key:multiplier, key:multiplier, etc.
LX_A= a:-1.0, d:1.0
LY_A= w:1.0, s:-1.0
RX_A= left:-1.0, right:1.0
RY_A= up:1.0, down:-1.0
LT_A= lshift:1.0
RT_A= del:1.0, capslock:1.0, f:1.0

[DigitalBinds]
; directly sets axis when held, range -255 to 255
LX_D=
LY_D=
RX_D=
RY_D=
LT_D= 
RT_D= 

[Settings]
; can be comma separated list, keep empty to run without window focus detection
exeName="Demon Tides.exe"
; locks mouse inside window
EnableMouseLock=1
; for mouse steering
MouseSteeringAxisX=
MouseSteeringAxisY=
EnableCursorReplacement=0
EnableVerticalLine=0
; mouse steer box, 1.0 means square
MouseSteerWidth=1.0
; lock mouse to digital input position
LX_D_MovesMouse=0
; 0 = Analog keys add to mouse steer, 1 = override
AnalogSupersedesMouse=0
; wooting and xinput analog start, 0-255
WootingDeadzone=4
ExtStickDeadzone=8
ExtTriggerDeadzone=8
; anti-deadzones, 0-100
LX_Antideadzone=0
LY_Antideadzone=0
RX_Antideadzone=0
RY_Antideadzone=0
LT_Antideadzone=0
RT_Antideadzone=0

AHITranslateMouseToAxes=1
AHIMouseAxisX=RX
AHIMouseAxisY=RY, 0.25
AHIMouseSensitivity=0.25
AHIMouseDecay=0.9



; === !!! Not ini format, must be placed at bottom ===
[CustomAutoexecute]

[CustomSubroutine]
#If WinActive("ahk_group ActiveGameGroup")
; Put Keyboard binds here (mouse binds are further below)
; AHI mouse binds: ahiOnLButton/RButton/MButton/XButton1/XButton2/Wheel - if one of these is missing, the corresponding key will not be intercepted and can be rebound normally but will not receive raw input protection
*w::
*a::
*s::
*d::
*up::
*down::
*left::
*right::
*f::
*del::
*lshift::return
*lbutton::return ; don't trigger switch to keyboard when focusing on window
*mbutton::return
*5:: 
	pad.Buttons.Start.SetState(1)
	KeyWait, 5
    pad.Buttons.Start.SetState(0)
	return
*6:: 
	pad.Buttons.Back.SetState(1)
	KeyWait, 6
    pad.Buttons.Back.SetState(0)
	return
*space:: 
	pad.Buttons.A.SetState(1)
	KeyWait, Space
    pad.Buttons.A.SetState(0)
	return
*q:: 
	pad.Buttons.X.SetState(1)
	KeyWait, q
    pad.Buttons.X.SetState(0)
	return
*e:: 
	pad.Buttons.B.SetState(1)
	KeyWait, e
    pad.Buttons.B.SetState(0)
	return
*x:: 
	pad.Buttons.Y.SetState(1)
	KeyWait, x
    pad.Buttons.Y.SetState(0)
	return
*z:: 
	pad.Buttons.LB.SetState(1)
	KeyWait, z
    pad.Buttons.LB.SetState(0)
	return
*c:: 
	pad.Buttons.RB.SetState(1)
	KeyWait, c
    pad.Buttons.RB.SetState(0)
	return
*2:: 
	pad.Dpad.SetState("Up")
	KeyWait, 2
    pad.Dpad.SetState("None")
	return
*1:: 
	pad.Dpad.SetState("Left")
	KeyWait, 1
    pad.Dpad.SetState("None")
	return
*3:: 
	pad.Dpad.SetState("Down")
	KeyWait, 3
    pad.Dpad.SetState("None")
	return
*4:: 
	pad.Dpad.SetState("Right")
	KeyWait, 4
    pad.Dpad.SetState("None")
	return
*lctrl::
	pad.Buttons.LB.SetState(1)
	KeyWait, lctrl
	pad.Buttons.LB.SetState(0)
	return

ahiOnLButton(start){
    if start {
        pad.Axes.RT.SetState(255)
	}
    else {
        pad.Axes.RT.SetState(0)
	}
}
ahiOnRButton(start){
    if start {
        pad.Buttons.LB.SetState(1)
	}
    else {
        pad.Buttons.LB.SetState(0)
	}
}
ahiOnMButton(start){
    if start {
        pad.Buttons.RS.SetState(1)
	}
    else {
        pad.Buttons.RS.SetState(0)
	}
}
ahiOnWheel(direction) {
	if (direction == 1) {
		; Wheel Up
		pad.Axes.RY.SetState(16000)
		sleep, 50
		pad.Axes.RY.SetState(0)
	} else if (direction == -1) {
		; Wheel Down
		pad.Axes.RY.SetState(-16000)
		sleep, 50
		pad.Axes.RY.SetState(0)
}} 
#If

; fallback if AutoHotInterception is disabled (Grid Legends in particular has too aggressive input reading though, so Right Click will always move the camera without AHI)
#If (WinActive("ahk_group ActiveGameGroup") && global EnableAHI == false)
#If
#If ; Ensures this is completely global
