[AnalogBinds]
; for wooting - axis = key:multiplier, key:multiplier, etc.
LX_A= a:-1.0, d:1.0
LY_A= w:1.0, s:-1.0
RX_A=
RY_A=
LT_A=
RT_A=

[DigitalBinds]
; directly sets axis when held, range -255 to 255
LX_D=
LY_D=
RX_D=
RY_D=
LT_D= 
RT_D= 

[Settings]
; can be comma separated list, keep empty to run without window focus detection
exeName=Demon Tides.exe, notepad.exe
; locks mouse inside window
EnableMouseLock=1
; for mouse steering
MouseSteeringAxisX=
MouseSteeringAxisY=
EnableCursorReplacement=0
EnableVerticalLine=0
; mouse steer box, 1.0 means square
MouseSteerWidth=1.0
; lock mouse to digital input position
LX_D_MovesMouse=0
; 0 = Analog keys add to mouse steer, 1 = override
AnalogSupersedesMouse=0
; wooting and xinput analog start, 0-255
WootingDeadzone=0
ExtStickDeadzone=8
ExtTriggerDeadzone=8
; anti-deadzones, 0-100
LX_Antideadzone=0
LY_Antideadzone=0
RX_Antideadzone=0
RY_Antideadzone=0
LT_Antideadzone=0
RT_Antideadzone=0

; use first option without assigning axes to simply turn off mouse movement
AHITranslateMouseToAxes=0
AHIMouseAxisX=RX
AHIMouseAxisY=RY
AHIMouseSensitivity=6.66
; 0.01 to 0.99, I don't think 0 and 1 are safe
AHIMouseDecay=0.99



; === !!! Not ini format, must be placed at bottom ===
[CustomAutoexecute]

[CustomSubroutine]
#If WinActive("ahk_group ActiveGameGroup")
; Put Keyboard binds here (mouse binds are further below)
; AHI mouse binds: ahiOnLButton/RButton/MButton/XButton1/XButton2/Wheel - if one of these is missing, the corresponding key will not be intercepted and can be rebound normally but will not receive raw input protection
*w::
*a::
*s::
*d::return
*lshift::o
#If

; fallback if AutoHotInterception is disabled (Grid Legends in particular has too aggressive input reading though, so Right Click will always move the camera without AHI)
#If (WinActive("ahk_group ActiveGameGroup") && global EnableAHI == false)
#If
#If ; Ensures this is completely global
