[AnalogBinds]
; wooting binds: axis = key:multiplier, key:multiplier, etc.
LX_A=
LY_A=
RX_A=
RY_A=
LT_A=
RT_A=

[DigitalBinds]
; directly sets axis when held, range -255 to 255
LX_D=q:-170.85, e:170.85
LY_D=
RX_D=
RY_D=
LT_D=space:255, xbutton2:171, xbutton1:84
RT_D=capslock:255, lshift:171, ctrl:84

[Settings]
; can be comma separated list, keep empty to run without window focus detection
exeName=fh6, notepad.exe
; locks mouse inside window
EnableMouseLock=1
; for racing games
EnableMouseSteering=1
EnableCursorReplacement=1
EnableVerticalLine=1
; mouse steer box, 1.0 means square
MouseSteerWidth=1.0
; steering must be either rbutton, lbutton, mbutton, xbutton1, xbutton2
SteeringKey=RButton
; lock mouse to digital input position
LX_D_MovesMouse=0
; 0 = Analog keys add to mouse steer, 1 = override
AnalogSupersedesMouse=0
; wooting and xinput analog start, 0-255
WootingDeadzone=8
ExtStickDeadzone=0
ExtTriggerDeadzone=0
; anti-deadzones, 0-100
LX_Antideadzone=15
LY_Antideadzone=0
RX_Antideadzone=0
RY_Antideadzone=0
LT_Antideadzone=0
RT_Antideadzone=0



; === !!! Not ini format, must be placed at bottom ===
[CustomCode]
#If WinActive("ahk_group ActiveGameGroup")
*rbutton::return
*c::enter
*`::esc
*capslock::return
*g::Click, Right Down
*g up::Click, Right Up
*Space::Enter
~*lbutton::b
*mbutton::,
*WheelUp::
    Send, {Up down}
    Sleep, 25
    Send, {Up up}
    Sleep, 25
    return
*WheelDown::
    Send, {Down down}
    Sleep, 25
    Send, {Down up}
    Sleep, 25
    return
*WheelLeft::WheelUp
*WheelRight::WheelDown

#If