[GlobalSettings]

; alternative config names for the input box
configAliases= 1:GridLegends, gl:GridLegends
; auto-fills input box if exe is detected
exeMatches= [test.exe,GridLegends.exe]:GridLegends, fh5.exe:ForzaH5
; ExternalXInputEnabled is best used with HidHide set for ahk interpreter (check task manager, usually it's AutoHotkeyU64.exe) - without HidHide, there will be multiple gamepads recognized - Note: HidHide may fail on Windows 11.
ExternalXInputEnabled=1
WootingEnabled=1