[AnalogBinds]
; axis = key:multiplier, key:multiplier, etc.
LX_A=a:-1.0, d:1.0
LY_A=w:1.0, s:-1.0
RX_A=j:-1.0, l:1.0
RY_A=i:1.0, k:-1.0
LT_A=LShift:1.0, LCtrl:1.0
RT_A=Space:1.0

[DigitalBinds]
; directly sets axis when held, range -255 to 255
LX_D=q:-170.85, e:170.85
LY_D=
RX_D=
RY_D=
LT_D=
RT_D=

[Settings]
; keep exeName empty to run without window focus detection
exeName=GridLegends.exe, notepad.exe
EnableCursorReplacement=1
EnableMouseLock=1
EnableVerticalLine=1
EnableMouseSteering=1
; mouse steer box, 1.0 means square
MouseSteerWidth=1.0
; lock mouse to digital input position
LX_D_MovesMouse=0
; 0 = Analog keys add to mouse steer, 1 = override
WootingSupersedesMouse=0
; Wooting and XInput analog start, 0-255
WootingDeadzone=8
ExtStickDeadzone=8
ExtTriggerDeadzone=8
; Anti-Deadzones, 0-100
LX_Antideadzone=20
LY_Antideadzone=0
RX_Antideadzone=15
RY_Antideadzone=0
LT_Antideadzone=50
RT_Antideadzone=50



; === !!! Not ini format, must be placed at bottom ===
[CustomCode]
#If WinActive("ahk_group ActiveGameGroup")
*Space::Enter
~*lbutton::F10 
~*w::F10 
*mbutton::,
*WheelUp::
    Send, {Up down}
    Sleep, 25
    Send, {Up up}
    Sleep, 25
    return
*WheelDown::
    Send, {Down down}
    Sleep, 25
    Send, {Down up}
    Sleep, 25
    return
	; (Note: SendRButton(1) relies on AutoHotInterception which is in the main script. This is an alternative)
*g::Click, Right Down
*g up::Click, Right Up
*z::
    Send, {Enter down}
    Sleep, 20
    Send, {Enter up}
    Sleep, 20
    Return
*x:: ; Turbo Controller B, lets you skip menus and jack off the handbrake
	SendPadBtn("B", 1)
    Sleep, 20
    SendPadBtn("B", 0)
    return
*1::F1
*2::F2
*5:: ; restart race
    Sleep, 10
    BlockInput, MouseMove
    Sleep, 1
    Send, {Esc down}
    Sleep, 20
    Send, {Esc up}
    Sleep, 20
    Send, {Down down}
    Sleep, 20
    Send, {Down up}
    Sleep, 20
    Send, {Enter down}
    Sleep, 20
    Send, {Enter up}
    Sleep, 250
    Send, {Up down}
    Sleep, 20
    Send, {Up up}
    Sleep, 20
    Send, {Enter down}
    Sleep, 20
    Send, {Enter up}
    Sleep, 1
    BlockInput, MouseMoveOff
    Sleep, 1
    Return
#If