; Grid Legends
; === Wooting Analog Binds ===
LX_A := {"a": -1.0, "d": 1.0}, LY_A := {"w": 1.0, "s": -1.0}
RX_A := {"j": -1.0, "l": 1.0}, RY_A := {"i": 1.0, "k": -1.0}
LT_A := {"LCtrl": 1.0}, RT_A := {"Space": 1.0}
; === Digital Key to Analog Binds ===
LX_D := [ ["q", -67*2.55], ["e", 67*2.55] ]
LY_D := [], RX_D := [], RY_D := [], LT_D := []
RT_D := [ ["lshift", 67*2.55] ]

; === Settings ===
exeName := "GridLegends.exe"
EnableMouseSteering := true
MouseSteerWidth := 1.0
LX_D_MovesMouse := false
WootingSupersedesMouse := false
LX_Antideadzone := 20
LY_Antideadzone := 0
RX_Antideadzone := 15
RY_Antideadzone := 0
LT_Antideadzone := 50
RT_Antideadzone := 64
EnableCursorReplacement := true
EnableMouseLock := true
EnableVerticalLine  := true

; no comments allowed below
ProfileSpecificBinds := "
(
#If WinActive(""ahk_exe "" . exeName)
~*lbutton::F10
*mbutton::,
*WheelUp::
    Send, {Up down}
    Sleep, 25
    Send, {Up up}
    Sleep, 25
    return
*WheelDown::
    Send, {Down down}
    Sleep, 25
    Send, {Down up}
    Sleep, 25
    return
*g::SendRButton(1)
*g up::SendRButton(0)
*z:: ; turbo enter
    Send, {Enter}
    Sleep, 1
    Return
*x:: ; Turbo Controller B
    pad.Buttons.B.SetState(1)
    Sleep, 1
    pad.Buttons.B.SetState(0)
    Sleep, 1
    Return
*`:: ; restart race macro
    BlockInput, MouseMove
    Sleep, 1
    Send, {Esc}{Down}{Enter}
    Sleep, 250
    Send, {Up}{Enter}
    BlockInput, MouseMoveOff
    Sleep, 1
    Return
#If
)"